"""Initial_tables_sqlite

Revision ID: 13dab08d6c6b
Revises:
Create Date: 2026-01-28 20:13:38.373084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dab08d6c6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('audio_file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corrected_transcripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transcription_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('corrected_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('correction_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_transcripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transcription_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_timestamps', sa.JSON(), nullable=True),
    sa.Column('confidence_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_samples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('audio_segment_path', sa.String(), nullable=True),
    sa.Column('ground_truth_text', sa.Text(), nullable=True),
    sa.Column('audio_quality', sa.String(), nullable=True),
    sa.Column('has_background_noise', sa.Boolean(), nullable=True),
    sa.Column('speaker_accent', sa.String(), nullable=True),
    sa.Column('times_used_in_training', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('source_transcription_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['source_transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcription_errors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transcription_id', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('predicted_text', sa.Text(), nullable=True),
    sa.Column('correct_text', sa.Text(), nullable=True),
    sa.Column('predicted_start_time', sa.Float(), nullable=True),
    sa.Column('predicted_end_time', sa.Float(), nullable=True),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('audio_quality_score', sa.Float(), nullable=True),
    sa.Column('background_noise_level', sa.Float(), nullable=True),
    sa.Column('speaker_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription_errors')
    op.drop_table('training_samples')
    op.drop_table('raw_transcripts')
    op.drop_table('corrected_transcripts')
    op.drop_table('transcriptions')
    # ### end Alembic commands ###
